/*

CREATE TABLE USUARIOS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(128),
	LOGIN VARCHAR(32),
	SENHA VARCHAR(64),
    DATA_CADASTRO TIMESTAMP,
	DATA_ATUALIZACAO TIMESTAMP,
	NOME_ATUALIZACAO VARCHAR(128)
);

*/

insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario I', 	'administrador', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario II', 	'coordenador', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario III', 'vendedor', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario IV', 	'usuario', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario V', 	'usuario V', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario VI',  'usuario VI', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario VII', 'gerente', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario VIII','diretor', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
insert into USUARIOS (NOME, LOGIN, SENHA, DATA_CADASTRO, DATA_ATUALIZACAO, NOME_ATUALIZACAO, NOME_CADASTRO) values ('usuario IX',  'restrito', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');